Portfolio: mobile version finished
Alexr16/Portfolio pull request #2
Opened 2022-02-11 18:06 UTC by Alexr16

Works section added.
About myself added.
Elements in Works section lay outed with CSS Grid and Flexbox combined.
`ul` and `li` used for listed categories in About myself section.

2022-02-11 18:27 UTC, MrBrN197 reviewed
## Hi, @Alexr16  👋 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that that has linter errors. please fix the linter errors and then ask for a re-review.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-02-11 18:37 UTC, Alexr16 commented
linters errors solved.

2022-02-11 19:36 UTC, elmar8287 requested changes
Hi @Alexr16, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  Check the comments under the review.
- [ ]  Please, consider fixing the horizontal scrolling on your page. It seems, the issue is with the background.
![2022-02-11 23 31 44](https://user-images.githubusercontent.com/49064106/153657626-e5fe265a-60ef-47f0-9067-fde14f53ddda.gif)


## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 19:36 UTC, elmar8287 commented on styles.css
> +}
- [ ] Please, consider that the hover should be as follows, as in the Figma template:
```
.button:hover {
  background-color: #FFF5E1;
  color: #F55800;
  border: 1px solid #F55800;
  box-sizing: border-box;
}
```

2022-02-11 19:36 UTC, elmar8287 commented on index.html
> +                    </div>
- [ ] Please, consider that the list of project technologies (e.g., "JavasScript", "HTML" and "CSS") are a list `ul` and each of them a `li`

2022-02-11 19:36 UTC, elmar8287 commented on index.html
> +            <h1>About me</h1>
- [ ] Please, consider that you could have one `h1` on your webpage. All other headers should have `hx` tag (aka h1, h2, h3, etc..) - try to replace it everywhere in your code.

2022-02-12 00:36 UTC, Alexr16 commented
Horizontal scrolling fixed repaired.
Hover changed.
List of project technologies (e.g., "JavasScript", "HTML" and "CSS") made with list `ul` and `li`.
Header tags `hx` changed.

2022-02-12 01:31 UTC, codepantherr requested changes
Hi @Alexr16 👋 , 

Great work on making most of the changes requested by the previous reviewer 👏 
but there is still one that has not been fully addressed.

## Suggested changes

- [ ] Though I appreciate your effort in trying to fix the horizontal scrolling issue, it hasn't been fully resolved yet. Kindly look at this [resource](https://www.codegrepper.com/code-examples/css/html+fix+horizontal+scroll) for a pointer to what you may be missing

![image](https://user-images.githubusercontent.com/46839548/153690331-38006759-9588-4c18-98b2-3ed6299011a5.png)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [ ] It would be nice to have detailed steps to clone a local copy of your repo.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-02-12 02:22 UTC, Alexr16 commented
Horizontal issue scrolling issue solved.

2022-02-12 02:38 UTC, Lordkaito approved these changes
Hi @Alexr16, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

- [ ] [OPTIONAL] Even though you mostly solved the horizontal scrolling, there is a still some when the screen is not big enough, so I would recommend to apply this properties to your `headline-ilustration` container:
```
headline-ilustration {
  display: flex;
  align-items: center (or you can use flex-end as well, not a big deal here)
  justify-content: flex-end (here it is necessary to apply flex-end)
}
```
And also apply this to the image inside this container:
```
.headline-img {
  width: 60%;
  /* margin: auto; */ (you can remove this one)
  position: relative;
  /* left: 190px; */ (you need to remove this one)
  top: 160px;
}
``` 
With that your problem should be completely gone!

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-02-12 03:02 UTC, merged